### ISSUE TITLE
My experimental edit to the file splitting code

### ISSUE THREAD

**Issue by julian2001** [julian2001/watsonScripts#8]
This is just my personal edit that is separate from the code

**Comment by julian2001** [comment]
[experimental file splitter julian2.pdf](https://github.com/julian2001/watsonScripts/files/3589794/experimental.file.splitter.julian2.pdf)

Check it out

**Comment by hasandiwan** [comment]
Why are you publishing python code as a PDF?!? I'd suggest creating a separate branch here and put your stuff there

**Comment by julian2001** [comment]
Did my notes help?
