### ISSUE TITLE
Give me write access to the repository

### ISSUE THREAD

**Issue by hasandiwan** [julian2001/watsonScripts#9]

**Comment by julian2001** [comment]
1. I didnt know what you meant by endnotes. I think its a good idea to keep the sale of the company one but its not absolutely necessary.
[Founder agrmt sept 10 julian hasan 5am.pdf](https://github.com/julian2001/watsonScripts/files/3598112/Founder.agrmt.sept.10.julian.hasan.5am.pdf)
